spring:
  application:
    name: Homefeeder
server:
  port: 13005
  servlet:
    context-path: /homefeeder
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false